<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class JobInputDocument {

  static $swaggerTypes = array(    
    'status' => 'string',
    'output_formats' => 'string',
    'type' => 'string',
    'access' => 'string',
    'url' => 'string',
    'version' => 'int',
    'file_type' => 'string',
    'id' => 'float',
    'guid' => 'string',
    'proc_date' => 'int',
    'name' => 'string',
    'outputs' => 'array<JobOutputDocument>',
    'actions' => 'string'   
    );


    /**
     * 
     */
	 public $status;// string


    /**
     * 
     */
	 public $output_formats;// string


    /**
     * 
     */
	 public $type;// string


    /**
     * 
     */
	 public $access;// string


    /**
     * 
     */
	 public $url;// string


    /**
     * 
     */
	 public $version;// int


    /**
     * 
     */
	 public $file_type;// string


    /**
     * 
     */
	 public $id;// float


    /**
     * 
     */
	 public $guid;// string


    /**
     * 
     */
	 public $proc_date;// int


    /**
     * 
     */
	 public $name;// string


    /**
     * 
     */
	 public $outputs =  array();// array<JobOutputDocument>


    /**
     * 
     */
	 public $actions;// string


}

?>