<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SignatureTemplateFieldInfo {

  static $swaggerTypes = array(    
    'regularExpression' => 'string',
    'mandatory' => 'bool',
    'graphSizeH' => 'int',
    'textRows' => 'float',
    'id' => 'string',
    'templateId' => 'string',
    'input' => 'float',
    'textColumns' => 'float',
    'recipientId' => 'string',
    'order' => 'float',
    'locations' => 'array<SignatureTemplateFieldLocationInfo>',
    'signatureFieldId' => 'float',
    'name' => 'string',
    'graphSizeW' => 'int'   
    );


    /**
     * 
     */
	 public $regularExpression;// string


    /**
     * 
     */
	 public $mandatory;// bool


    /**
     * 
     */
	 public $graphSizeH;// int


    /**
     * 
     */
	 public $textRows;// float


    /**
     * 
     */
	 public $id;// string


    /**
     * 
     */
	 public $templateId;// string


    /**
     * 
     */
	 public $input;// float


    /**
     * 
     */
	 public $textColumns;// float


    /**
     * 
     */
	 public $recipientId;// string


    /**
     * 
     */
	 public $order;// float


    /**
     * 
     */
	 public $locations =  array();// array<SignatureTemplateFieldLocationInfo>


    /**
     * 
     */
	 public $signatureFieldId;// float


    /**
     * 
     */
	 public $name;// string


    /**
     * 
     */
	 public $graphSizeW;// int


}

?>