<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SignatureTemplateFieldSettings {

  static $swaggerTypes = array(    
    'textColumns' => 'float',
    'order' => 'int',
    'page' => 'int',
    'regex' => 'string',
    'mandatory' => 'bool',
    'name' => 'string',
    'locationX' => 'float',
    'graphSizeH' => 'float',
    'graphSizeW' => 'float',
    'locationY' => 'float',
    'textRows' => 'float'   
    );


    /**
     * 
     */
	 public $textColumns;// float


    /**
     * 
     */
	 public $order;// int


    /**
     * 
     */
	 public $page;// int


    /**
     * 
     */
	 public $regex;// string


    /**
     * 
     */
	 public $mandatory;// bool


    /**
     * 
     */
	 public $name;// string


    /**
     * 
     */
	 public $locationX;// float


    /**
     * 
     */
	 public $graphSizeH;// float


    /**
     * 
     */
	 public $graphSizeW;// float


    /**
     * 
     */
	 public $locationY;// float


    /**
     * 
     */
	 public $textRows;// float


}

?>