<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TestData {

  static $swaggerTypes = array(    
    'documentDetailsResponseList' => 'Array<DocumentDetailsResponse>',
    'changesResponseList' => 'Array<ChangesResponse>',
    'changesResultList' => 'Array<ChangesResult>',
    'documentDetailsResultList' => 'Array<DocumentDetailsResult>',
    'compareResultList' => 'Array<CompareResult>',
    'pageList' => 'Array<Page>',
    'compareResponseList' => 'Array<CompareResponse>',
    'rectangleList' => 'Array<Rectangle>',
    'changeInfoList' => 'Array<ChangeInfo>',
    'resetPasswordResultList' => 'Array<ResetPasswordResult>',
    'createUserResultList' => 'Array<CreateUserResult>',
    'userPasswordInfoList' => 'Array<UserPasswordInfo>',
    'updateStorageProviderResponseList' => 'Array<UpdateStorageProviderResponse>',
    'createUserResponseList' => 'Array<CreateUserResponse>',
    'changePasswordResultList' => 'Array<ChangePasswordResult>',
    'updateUserResponseList' => 'Array<UpdateUserResponse>',
    'addStorageProviderResponseList' => 'Array<AddStorageProviderResponse>',
    'updateUserResultList' => 'Array<UpdateUserResult>',
    'userInfoResponseList' => 'Array<UserInfoResponse>',
    'getStorageProvidersResultList' => 'Array<GetStorageProvidersResult>',
    'resetPasswordResponseList' => 'Array<ResetPasswordResponse>',
    'updateStorageProviderResultList' => 'Array<UpdateStorageProviderResult>',
    'userInfoList' => 'Array<UserInfo>',
    'addStorageProviderResultList' => 'Array<AddStorageProviderResult>',
    'getStorageProvidersResponseList' => 'Array<GetStorageProvidersResponse>',
    'userInfoResultList' => 'Array<UserInfoResult>',
    'storageProviderInfoList' => 'Array<StorageProviderInfo>',
    'changePasswordResponseList' => 'Array<ChangePasswordResponse>',
    'setCollaboratorsResponseList' => 'Array<SetCollaboratorsResponse>',
    'listRepliesResultList' => 'Array<ListRepliesResult>',
    'listAnnotationsResponseList' => 'Array<ListAnnotationsResponse>',
    'rangeList' => 'Array<Range>',
    'annotationInfoList' => 'Array<AnnotationInfo>',
    'getCollaboratorsResponseList' => 'Array<GetCollaboratorsResponse>',
    'userIdentityList' => 'Array<UserIdentity>',
    'moveAnnotationResultList' => 'Array<MoveAnnotationResult>',
    'editReplyResponseList' => 'Array<EditReplyResponse>',
    'addReplyResultList' => 'Array<AddReplyResult>',
    'addReplyResponseList' => 'Array<AddReplyResponse>',
    'createAnnotationResponseList' => 'Array<CreateAnnotationResponse>',
    'deleteAnnotationResultList' => 'Array<DeleteAnnotationResult>',
    'deleteAnnotationResponseList' => 'Array<DeleteAnnotationResponse>',
    'createAnnotationResultList' => 'Array<CreateAnnotationResult>',
    'annotationReplyInfoList' => 'Array<AnnotationReplyInfo>',
    'listRepliesResponseList' => 'Array<ListRepliesResponse>',
    'moveAnnotationResponseList' => 'Array<MoveAnnotationResponse>',
    'editReplyResultList' => 'Array<EditReplyResult>',
    'listAnnotationsResultList' => 'Array<ListAnnotationsResult>',
    'setCollaboratorsResultList' => 'Array<SetCollaboratorsResult>',
    'pointList' => 'Array<Point>',
    'getCollaboratorsResultList' => 'Array<GetCollaboratorsResult>',
    'resultList' => 'Array<Result>',
    'getJobsDocumentsResultList' => 'Array<GetJobsDocumentsResult>',
    'getJobDocumentsResultList' => 'Array<GetJobDocumentsResult>',
    'createJobResponseList' => 'Array<CreateJobResponse>',
    'getJobDocumentsResponseList' => 'Array<GetJobDocumentsResponse>',
    'createJobResultList' => 'Array<CreateJobResult>',
    'getJobsResponseList' => 'Array<GetJobsResponse>',
    'jobInputDocumentList' => 'Array<JobInputDocument>',
    'convertResponseList' => 'Array<ConvertResponse>',
    'getJobResponseList' => 'Array<GetJobResponse>',
    'addJobDocumentResponseList' => 'Array<AddJobDocumentResponse>',
    'getJobsDocumentsResponseList' => 'Array<GetJobsDocumentsResponse>',
    'getJobsResultList' => 'Array<GetJobsResult>',
    'updateJobResponseList' => 'Array<UpdateJobResponse>',
    'getJobResultList' => 'Array<GetJobResult>',
    'jobOutputDocumentList' => 'Array<JobOutputDocument>',
    'convertRequestResultList' => 'Array<ConvertRequestResult>',
    'jobDocumentsEntryList' => 'Array<JobDocumentsEntry>',
    'jobInfoList' => 'Array<JobInfo>',
    'addJobDocumentResultList' => 'Array<AddJobDocumentResult>',
    'viewDocumentResultList' => 'Array<ViewDocumentResult>',
    'viewDocumentResponseList' => 'Array<ViewDocumentResponse>',
    'dimensionList' => 'Array<Dimension>',
    'createPackageResultList' => 'Array<CreatePackageResult>',
    'uploadResponseList' => 'Array<UploadResponse>',
    'compressResponseList' => 'Array<CompressResponse>',
    'deleteResultList' => 'Array<DeleteResult>',
    'createFolderResultList' => 'Array<CreateFolderResult>',
    'folderMoveResultList' => 'Array<FolderMoveResult>',
    'fileMoveResultList' => 'Array<FileMoveResult>',
    'listEntitiesResultList' => 'Array<ListEntitiesResult>',
    'fileSystemDocumentList' => 'Array<FileSystemDocument>',
    'createFolderResponseList' => 'Array<CreateFolderResponse>',
    'documentInfoList' => 'Array<DocumentInfo>',
    'compressRequestResultList' => 'Array<CompressRequestResult>',
    'uploadRequestResultList' => 'Array<UploadRequestResult>',
    'storageInfoResultList' => 'Array<StorageInfoResult>',
    'createPackageResponseList' => 'Array<CreatePackageResponse>',
    'folderMoveResponseList' => 'Array<FolderMoveResponse>',
    'storageInfoResponseList' => 'Array<StorageInfoResponse>',
    'fileSystemFolderList' => 'Array<FileSystemFolder>',
    'deleteResponseList' => 'Array<DeleteResponse>',
    'listEntitiesResponseList' => 'Array<ListEntitiesResponse>',
    'fileMoveResponseList' => 'Array<FileMoveResponse>',
    'getDocumentInfoResultList' => 'Array<GetDocumentInfoResult>',
    'templateFieldList' => 'Array<TemplateField>',
    'documentViewsResultList' => 'Array<DocumentViewsResult>',
    'sharedDocumentsResponseList' => 'Array<SharedDocumentsResponse>',
    'templateFieldsResponseList' => 'Array<TemplateFieldsResponse>',
    'documentAccessInfoResultList' => 'Array<DocumentAccessInfoResult>',
    'sharedUsersResultList' => 'Array<SharedUsersResult>',
    'sharedDocumentsResultList' => 'Array<SharedDocumentsResult>',
    'documentViewsResponseList' => 'Array<DocumentViewsResponse>',
    'getDocumentForeignTypesResponseList' => 'Array<GetDocumentForeignTypesResponse>',
    'documentViewInfoList' => 'Array<DocumentViewInfo>',
    'sharedUsersResponseList' => 'Array<SharedUsersResponse>',
    'getDocumentInfoResponseList' => 'Array<GetDocumentInfoResponse>',
    'documentUserStatusResultList' => 'Array<DocumentUserStatusResult>',
    'documentUserStatusResponseList' => 'Array<DocumentUserStatusResponse>',
    'templateFieldsResultList' => 'Array<TemplateFieldsResult>',
    'getDocumentForeignTypesResultList' => 'Array<GetDocumentForeignTypesResult>',
    'documentAccessInfoResponseList' => 'Array<DocumentAccessInfoResponse>',
    'sharedDocumentInfoList' => 'Array<SharedDocumentInfo>',
    'questionnaireExecutionInfoList' => 'Array<QuestionnaireExecutionInfo>',
    'getQuestionnairesResponseList' => 'Array<GetQuestionnairesResponse>',
    'getDocumentQuestionnairesResultList' => 'Array<GetDocumentQuestionnairesResult>',
    'addDocumentDataSourceResponseList' => 'Array<AddDocumentDataSourceResponse>',
    'getDatasourceResultList' => 'Array<GetDatasourceResult>',
    'getDatasourcesResponseList' => 'Array<GetDatasourcesResponse>',
    'addDocumentQuestionnaireResponseList' => 'Array<AddDocumentQuestionnaireResponse>',
    'updateQuestionnaireResultList' => 'Array<UpdateQuestionnaireResult>',
    'addQuestionnaireExecutionResponseList' => 'Array<AddQuestionnaireExecutionResponse>',
    'deleteDatasourceResponseList' => 'Array<DeleteDatasourceResponse>',
    'createQuestionnaireResultList' => 'Array<CreateQuestionnaireResult>',
    'createQuestionnaireResponseList' => 'Array<CreateQuestionnaireResponse>',
    'questionnaireInfoList' => 'Array<QuestionnaireInfo>',
    'addDatasourceResultList' => 'Array<AddDatasourceResult>',
    'questionnairePageInfoList' => 'Array<QuestionnairePageInfo>',
    'updateQuestionnaireExecutionResponseList' => 'Array<UpdateQuestionnaireExecutionResponse>',
    'getQuestionnaireExecutionsResultList' => 'Array<GetQuestionnaireExecutionsResult>',
    'deleteQuestionnaireResultList' => 'Array<DeleteQuestionnaireResult>',
    'getDocumentQuestionnairesResponseList' => 'Array<GetDocumentQuestionnairesResponse>',
    'getDatasourceResponseList' => 'Array<GetDatasourceResponse>',
    'addQuestionnaireExecutionResultList' => 'Array<AddQuestionnaireExecutionResult>',
    'deleteDocumentQuestionnaireResponseList' => 'Array<DeleteDocumentQuestionnaireResponse>',
    'mergeTemplateResponseList' => 'Array<MergeTemplateResponse>',
    'deleteDocumentQuestionnaireResultList' => 'Array<DeleteDocumentQuestionnaireResult>',
    'getQuestionnairesResultList' => 'Array<GetQuestionnairesResult>',
    'getQuestionnaireExecutionsResponseList' => 'Array<GetQuestionnaireExecutionsResponse>',
    'deleteQuestionnaireResponseList' => 'Array<DeleteQuestionnaireResponse>',
    'questionInfoList' => 'Array<QuestionInfo>',
    'datasourceList' => 'Array<Datasource>',
    'getQuestionnaireResultList' => 'Array<GetQuestionnaireResult>',
    'mergeTemplateResultList' => 'Array<MergeTemplateResult>',
    'answerInfoList' => 'Array<AnswerInfo>',
    'getDatasourcesResultList' => 'Array<GetDatasourcesResult>',
    'updateQuestionnaireExecutionResultList' => 'Array<UpdateQuestionnaireExecutionResult>',
    'addDocumentDataSourceResultList' => 'Array<AddDocumentDataSourceResult>',
    'deleteDatasourceResultList' => 'Array<DeleteDatasourceResult>',
    'addDocumentQuestionnaireResultList' => 'Array<AddDocumentQuestionnaireResult>',
    'updateQuestionnaireResponseList' => 'Array<UpdateQuestionnaireResponse>',
    'addDatasourceResponseList' => 'Array<AddDatasourceResponse>',
    'getQuestionnaireResponseList' => 'Array<GetQuestionnaireResponse>',
    'datasourceFieldList' => 'Array<DatasourceField>',
    'renameResponseList' => 'Array<RenameResponse>',
    'renameResultList' => 'Array<RenameResult>',
    'signatureEnvelopeDocumentsResponseList' => 'Array<SignatureEnvelopeDocumentsResponse>',
    'signatureFieldInfoList' => 'Array<SignatureFieldInfo>',
    'signatureContactResponseList' => 'Array<SignatureContactResponse>',
    'signatureEnvelopesResultList' => 'Array<SignatureEnvelopesResult>',
    'signatureTemplateFieldLocationInfoList' => 'Array<SignatureTemplateFieldLocationInfo>',
    'signatureTemplateDocumentResultList' => 'Array<SignatureTemplateDocumentResult>',
    'signatureContactsResponseList' => 'Array<SignatureContactsResponse>',
    'signatureFieldResultList' => 'Array<SignatureFieldResult>',
    'signatureSignatureInfoList' => 'Array<SignatureSignatureInfo>',
    'signatureTemplateFieldsResponseList' => 'Array<SignatureTemplateFieldsResponse>',
    'signatureEnvelopeInfoList' => 'Array<SignatureEnvelopeInfo>',
    'signatureTemplateFieldSettingsList' => 'Array<SignatureTemplateFieldSettings>',
    'signatureTemplateFieldLocationSettingsList' => 'Array<SignatureTemplateFieldLocationSettings>',
    'signatureEnvelopeRecipientResultList' => 'Array<SignatureEnvelopeRecipientResult>',
    'signatureTemplateFieldResponseList' => 'Array<SignatureTemplateFieldResponse>',
    'signatureEnvelopesResponseList' => 'Array<SignatureEnvelopesResponse>',
    'signatureEnvelopeFieldInfoList' => 'Array<SignatureEnvelopeFieldInfo>',
    'signatureRoleInfoList' => 'Array<SignatureRoleInfo>',
    'signatureTemplateSettingsList' => 'Array<SignatureTemplateSettings>',
    'signatureTemplateFieldsResultList' => 'Array<SignatureTemplateFieldsResult>',
    'signatureContactsImportResultList' => 'Array<SignatureContactsImportResult>',
    'signatureEnvelopeFieldsResponseList' => 'Array<SignatureEnvelopeFieldsResponse>',
    'signatureTemplateDocumentInfoList' => 'Array<SignatureTemplateDocumentInfo>',
    'signatureFieldSettingsList' => 'Array<SignatureFieldSettings>',
    'signatureTemplateFieldInfoList' => 'Array<SignatureTemplateFieldInfo>',
    'signatureRolesResultList' => 'Array<SignatureRolesResult>',
    'signatureTemplateResultList' => 'Array<SignatureTemplateResult>',
    'signatureEnvelopeRecipientsResponseList' => 'Array<SignatureEnvelopeRecipientsResponse>',
    'signatureRolesResponseList' => 'Array<SignatureRolesResponse>',
    'signatureContactsImportResponseList' => 'Array<SignatureContactsImportResponse>',
    'signatureEnvelopeFieldsResultList' => 'Array<SignatureEnvelopeFieldsResult>',
    'signatureEnvelopeFieldResponseList' => 'Array<SignatureEnvelopeFieldResponse>',
    'signatureTemplateResponseList' => 'Array<SignatureTemplateResponse>',
    'signatureEnvelopeDocumentResponseList' => 'Array<SignatureEnvelopeDocumentResponse>',
    'signatureSignaturesResponseList' => 'Array<SignatureSignaturesResponse>',
    'signatureTemplatesResponseList' => 'Array<SignatureTemplatesResponse>',
    'signatureSignatureSettingsList' => 'Array<SignatureSignatureSettings>',
    'signatureEnvelopeResultList' => 'Array<SignatureEnvelopeResult>',
    'signatureTemplateDocumentResponseList' => 'Array<SignatureTemplateDocumentResponse>',
    'signatureTemplateRecipientsResultList' => 'Array<SignatureTemplateRecipientsResult>',
    'signatureContactResultList' => 'Array<SignatureContactResult>',
    'signatureEnvelopeRecipientResponseList' => 'Array<SignatureEnvelopeRecipientResponse>',
    'signatureTemplateRecipientsResponseList' => 'Array<SignatureTemplateRecipientsResponse>',
    'signatureEnvelopeFieldResultList' => 'Array<SignatureEnvelopeFieldResult>',
    'signatureTemplateDocumentsResultList' => 'Array<SignatureTemplateDocumentsResult>',
    'signatureEnvelopeResourcesResultList' => 'Array<SignatureEnvelopeResourcesResult>',
    'signatureEnvelopeDocumentsResultList' => 'Array<SignatureEnvelopeDocumentsResult>',
    'signatureTemplatesResultList' => 'Array<SignatureTemplatesResult>',
    'signatureEnvelopeRecipientsResultList' => 'Array<SignatureEnvelopeRecipientsResult>',
    'signatureFieldResponseList' => 'Array<SignatureFieldResponse>',
    'signatureFieldsResponseList' => 'Array<SignatureFieldsResponse>',
    'signatureStatusResponseList' => 'Array<SignatureStatusResponse>',
    'signatureEnvelopeFieldLocationInfoList' => 'Array<SignatureEnvelopeFieldLocationInfo>',
    'signatureContactsResultList' => 'Array<SignatureContactsResult>',
    'signatureEnvelopeDocumentInfoList' => 'Array<SignatureEnvelopeDocumentInfo>',
    'signatureTemplateRecipientInfoList' => 'Array<SignatureTemplateRecipientInfo>',
    'signatureTemplateDocumentsResponseList' => 'Array<SignatureTemplateDocumentsResponse>',
    'signatureSignatureResponseList' => 'Array<SignatureSignatureResponse>',
    'signatureEnvelopeDocumentResultList' => 'Array<SignatureEnvelopeDocumentResult>',
    'signatureTemplateFieldResultList' => 'Array<SignatureTemplateFieldResult>',
    'signatureTemplateInfoList' => 'Array<SignatureTemplateInfo>',
    'signatureSignatureResultList' => 'Array<SignatureSignatureResult>',
    'signatureFieldsResultList' => 'Array<SignatureFieldsResult>',
    'signatureContactSettingsList' => 'Array<SignatureContactSettings>',
    'signatureEnvelopeRecipientInfoList' => 'Array<SignatureEnvelopeRecipientInfo>',
    'signatureEnvelopeSettingsList' => 'Array<SignatureEnvelopeSettings>',
    'signatureEnvelopeFieldSettingsList' => 'Array<SignatureEnvelopeFieldSettings>',
    'signatureContactInfoList' => 'Array<SignatureContactInfo>',
    'signatureEnvelopeFieldLocationSettingsList' => 'Array<SignatureEnvelopeFieldLocationSettings>',
    'signatureEnvelopeResponseList' => 'Array<SignatureEnvelopeResponse>',
    'signatureSignaturesResultList' => 'Array<SignatureSignaturesResult>',
    'signatureEnvelopeResourcesResponseList' => 'Array<SignatureEnvelopeResourcesResponse>'   
    );


    /**
     * 
     */
	 public $documentDetailsResponseList;// Array<DocumentDetailsResponse>


    /**
     * 
     */
	 public $changesResponseList;// Array<ChangesResponse>


    /**
     * 
     */
	 public $changesResultList;// Array<ChangesResult>


    /**
     * 
     */
	 public $documentDetailsResultList;// Array<DocumentDetailsResult>


    /**
     * 
     */
	 public $compareResultList;// Array<CompareResult>


    /**
     * 
     */
	 public $pageList;// Array<Page>


    /**
     * 
     */
	 public $compareResponseList;// Array<CompareResponse>


    /**
     * 
     */
	 public $rectangleList;// Array<Rectangle>


    /**
     * 
     */
	 public $changeInfoList;// Array<ChangeInfo>


    /**
     * 
     */
	 public $resetPasswordResultList;// Array<ResetPasswordResult>


    /**
     * 
     */
	 public $createUserResultList;// Array<CreateUserResult>


    /**
     * 
     */
	 public $userPasswordInfoList;// Array<UserPasswordInfo>


    /**
     * 
     */
	 public $updateStorageProviderResponseList;// Array<UpdateStorageProviderResponse>


    /**
     * 
     */
	 public $createUserResponseList;// Array<CreateUserResponse>


    /**
     * 
     */
	 public $changePasswordResultList;// Array<ChangePasswordResult>


    /**
     * 
     */
	 public $updateUserResponseList;// Array<UpdateUserResponse>


    /**
     * 
     */
	 public $addStorageProviderResponseList;// Array<AddStorageProviderResponse>


    /**
     * 
     */
	 public $updateUserResultList;// Array<UpdateUserResult>


    /**
     * 
     */
	 public $userInfoResponseList;// Array<UserInfoResponse>


    /**
     * 
     */
	 public $getStorageProvidersResultList;// Array<GetStorageProvidersResult>


    /**
     * 
     */
	 public $resetPasswordResponseList;// Array<ResetPasswordResponse>


    /**
     * 
     */
	 public $updateStorageProviderResultList;// Array<UpdateStorageProviderResult>


    /**
     * 
     */
	 public $userInfoList;// Array<UserInfo>


    /**
     * 
     */
	 public $addStorageProviderResultList;// Array<AddStorageProviderResult>


    /**
     * 
     */
	 public $getStorageProvidersResponseList;// Array<GetStorageProvidersResponse>


    /**
     * 
     */
	 public $userInfoResultList;// Array<UserInfoResult>


    /**
     * 
     */
	 public $storageProviderInfoList;// Array<StorageProviderInfo>


    /**
     * 
     */
	 public $changePasswordResponseList;// Array<ChangePasswordResponse>


    /**
     * 
     */
	 public $setCollaboratorsResponseList;// Array<SetCollaboratorsResponse>


    /**
     * 
     */
	 public $listRepliesResultList;// Array<ListRepliesResult>


    /**
     * 
     */
	 public $listAnnotationsResponseList;// Array<ListAnnotationsResponse>


    /**
     * 
     */
	 public $rangeList;// Array<Range>


    /**
     * 
     */
	 public $annotationInfoList;// Array<AnnotationInfo>


    /**
     * 
     */
	 public $getCollaboratorsResponseList;// Array<GetCollaboratorsResponse>


    /**
     * 
     */
	 public $userIdentityList;// Array<UserIdentity>


    /**
     * 
     */
	 public $moveAnnotationResultList;// Array<MoveAnnotationResult>


    /**
     * 
     */
	 public $editReplyResponseList;// Array<EditReplyResponse>


    /**
     * 
     */
	 public $addReplyResultList;// Array<AddReplyResult>


    /**
     * 
     */
	 public $addReplyResponseList;// Array<AddReplyResponse>


    /**
     * 
     */
	 public $createAnnotationResponseList;// Array<CreateAnnotationResponse>


    /**
     * 
     */
	 public $deleteAnnotationResultList;// Array<DeleteAnnotationResult>


    /**
     * 
     */
	 public $deleteAnnotationResponseList;// Array<DeleteAnnotationResponse>


    /**
     * 
     */
	 public $createAnnotationResultList;// Array<CreateAnnotationResult>


    /**
     * 
     */
	 public $annotationReplyInfoList;// Array<AnnotationReplyInfo>


    /**
     * 
     */
	 public $listRepliesResponseList;// Array<ListRepliesResponse>


    /**
     * 
     */
	 public $moveAnnotationResponseList;// Array<MoveAnnotationResponse>


    /**
     * 
     */
	 public $editReplyResultList;// Array<EditReplyResult>


    /**
     * 
     */
	 public $listAnnotationsResultList;// Array<ListAnnotationsResult>


    /**
     * 
     */
	 public $setCollaboratorsResultList;// Array<SetCollaboratorsResult>


    /**
     * 
     */
	 public $pointList;// Array<Point>


    /**
     * 
     */
	 public $getCollaboratorsResultList;// Array<GetCollaboratorsResult>


    /**
     * 
     */
	 public $resultList;// Array<Result>


    /**
     * 
     */
	 public $getJobsDocumentsResultList;// Array<GetJobsDocumentsResult>


    /**
     * 
     */
	 public $getJobDocumentsResultList;// Array<GetJobDocumentsResult>


    /**
     * 
     */
	 public $createJobResponseList;// Array<CreateJobResponse>


    /**
     * 
     */
	 public $getJobDocumentsResponseList;// Array<GetJobDocumentsResponse>


    /**
     * 
     */
	 public $createJobResultList;// Array<CreateJobResult>


    /**
     * 
     */
	 public $getJobsResponseList;// Array<GetJobsResponse>


    /**
     * 
     */
	 public $jobInputDocumentList;// Array<JobInputDocument>


    /**
     * 
     */
	 public $convertResponseList;// Array<ConvertResponse>


    /**
     * 
     */
	 public $getJobResponseList;// Array<GetJobResponse>


    /**
     * 
     */
	 public $addJobDocumentResponseList;// Array<AddJobDocumentResponse>


    /**
     * 
     */
	 public $getJobsDocumentsResponseList;// Array<GetJobsDocumentsResponse>


    /**
     * 
     */
	 public $getJobsResultList;// Array<GetJobsResult>


    /**
     * 
     */
	 public $updateJobResponseList;// Array<UpdateJobResponse>


    /**
     * 
     */
	 public $getJobResultList;// Array<GetJobResult>


    /**
     * 
     */
	 public $jobOutputDocumentList;// Array<JobOutputDocument>


    /**
     * 
     */
	 public $convertRequestResultList;// Array<ConvertRequestResult>


    /**
     * 
     */
	 public $jobDocumentsEntryList;// Array<JobDocumentsEntry>


    /**
     * 
     */
	 public $jobInfoList;// Array<JobInfo>


    /**
     * 
     */
	 public $addJobDocumentResultList;// Array<AddJobDocumentResult>


    /**
     * 
     */
	 public $viewDocumentResultList;// Array<ViewDocumentResult>


    /**
     * 
     */
	 public $viewDocumentResponseList;// Array<ViewDocumentResponse>


    /**
     * 
     */
	 public $dimensionList;// Array<Dimension>


    /**
     * 
     */
	 public $createPackageResultList;// Array<CreatePackageResult>


    /**
     * 
     */
	 public $uploadResponseList;// Array<UploadResponse>


    /**
     * 
     */
	 public $compressResponseList;// Array<CompressResponse>


    /**
     * 
     */
	 public $deleteResultList;// Array<DeleteResult>


    /**
     * 
     */
	 public $createFolderResultList;// Array<CreateFolderResult>


    /**
     * 
     */
	 public $folderMoveResultList;// Array<FolderMoveResult>


    /**
     * 
     */
	 public $fileMoveResultList;// Array<FileMoveResult>


    /**
     * 
     */
	 public $listEntitiesResultList;// Array<ListEntitiesResult>


    /**
     * 
     */
	 public $fileSystemDocumentList;// Array<FileSystemDocument>


    /**
     * 
     */
	 public $createFolderResponseList;// Array<CreateFolderResponse>


    /**
     * 
     */
	 public $documentInfoList;// Array<DocumentInfo>


    /**
     * 
     */
	 public $compressRequestResultList;// Array<CompressRequestResult>


    /**
     * 
     */
	 public $uploadRequestResultList;// Array<UploadRequestResult>


    /**
     * 
     */
	 public $storageInfoResultList;// Array<StorageInfoResult>


    /**
     * 
     */
	 public $createPackageResponseList;// Array<CreatePackageResponse>


    /**
     * 
     */
	 public $folderMoveResponseList;// Array<FolderMoveResponse>


    /**
     * 
     */
	 public $storageInfoResponseList;// Array<StorageInfoResponse>


    /**
     * 
     */
	 public $fileSystemFolderList;// Array<FileSystemFolder>


    /**
     * 
     */
	 public $deleteResponseList;// Array<DeleteResponse>


    /**
     * 
     */
	 public $listEntitiesResponseList;// Array<ListEntitiesResponse>


    /**
     * 
     */
	 public $fileMoveResponseList;// Array<FileMoveResponse>


    /**
     * 
     */
	 public $getDocumentInfoResultList;// Array<GetDocumentInfoResult>


    /**
     * 
     */
	 public $templateFieldList;// Array<TemplateField>


    /**
     * 
     */
	 public $documentViewsResultList;// Array<DocumentViewsResult>


    /**
     * 
     */
	 public $sharedDocumentsResponseList;// Array<SharedDocumentsResponse>


    /**
     * 
     */
	 public $templateFieldsResponseList;// Array<TemplateFieldsResponse>


    /**
     * 
     */
	 public $documentAccessInfoResultList;// Array<DocumentAccessInfoResult>


    /**
     * 
     */
	 public $sharedUsersResultList;// Array<SharedUsersResult>


    /**
     * 
     */
	 public $sharedDocumentsResultList;// Array<SharedDocumentsResult>


    /**
     * 
     */
	 public $documentViewsResponseList;// Array<DocumentViewsResponse>


    /**
     * 
     */
	 public $getDocumentForeignTypesResponseList;// Array<GetDocumentForeignTypesResponse>


    /**
     * 
     */
	 public $documentViewInfoList;// Array<DocumentViewInfo>


    /**
     * 
     */
	 public $sharedUsersResponseList;// Array<SharedUsersResponse>


    /**
     * 
     */
	 public $getDocumentInfoResponseList;// Array<GetDocumentInfoResponse>


    /**
     * 
     */
	 public $documentUserStatusResultList;// Array<DocumentUserStatusResult>


    /**
     * 
     */
	 public $documentUserStatusResponseList;// Array<DocumentUserStatusResponse>


    /**
     * 
     */
	 public $templateFieldsResultList;// Array<TemplateFieldsResult>


    /**
     * 
     */
	 public $getDocumentForeignTypesResultList;// Array<GetDocumentForeignTypesResult>


    /**
     * 
     */
	 public $documentAccessInfoResponseList;// Array<DocumentAccessInfoResponse>


    /**
     * 
     */
	 public $sharedDocumentInfoList;// Array<SharedDocumentInfo>


    /**
     * 
     */
	 public $questionnaireExecutionInfoList;// Array<QuestionnaireExecutionInfo>


    /**
     * 
     */
	 public $getQuestionnairesResponseList;// Array<GetQuestionnairesResponse>


    /**
     * 
     */
	 public $getDocumentQuestionnairesResultList;// Array<GetDocumentQuestionnairesResult>


    /**
     * 
     */
	 public $addDocumentDataSourceResponseList;// Array<AddDocumentDataSourceResponse>


    /**
     * 
     */
	 public $getDatasourceResultList;// Array<GetDatasourceResult>


    /**
     * 
     */
	 public $getDatasourcesResponseList;// Array<GetDatasourcesResponse>


    /**
     * 
     */
	 public $addDocumentQuestionnaireResponseList;// Array<AddDocumentQuestionnaireResponse>


    /**
     * 
     */
	 public $updateQuestionnaireResultList;// Array<UpdateQuestionnaireResult>


    /**
     * 
     */
	 public $addQuestionnaireExecutionResponseList;// Array<AddQuestionnaireExecutionResponse>


    /**
     * 
     */
	 public $deleteDatasourceResponseList;// Array<DeleteDatasourceResponse>


    /**
     * 
     */
	 public $createQuestionnaireResultList;// Array<CreateQuestionnaireResult>


    /**
     * 
     */
	 public $createQuestionnaireResponseList;// Array<CreateQuestionnaireResponse>


    /**
     * 
     */
	 public $questionnaireInfoList;// Array<QuestionnaireInfo>


    /**
     * 
     */
	 public $addDatasourceResultList;// Array<AddDatasourceResult>


    /**
     * 
     */
	 public $questionnairePageInfoList;// Array<QuestionnairePageInfo>


    /**
     * 
     */
	 public $updateQuestionnaireExecutionResponseList;// Array<UpdateQuestionnaireExecutionResponse>


    /**
     * 
     */
	 public $getQuestionnaireExecutionsResultList;// Array<GetQuestionnaireExecutionsResult>


    /**
     * 
     */
	 public $deleteQuestionnaireResultList;// Array<DeleteQuestionnaireResult>


    /**
     * 
     */
	 public $getDocumentQuestionnairesResponseList;// Array<GetDocumentQuestionnairesResponse>


    /**
     * 
     */
	 public $getDatasourceResponseList;// Array<GetDatasourceResponse>


    /**
     * 
     */
	 public $addQuestionnaireExecutionResultList;// Array<AddQuestionnaireExecutionResult>


    /**
     * 
     */
	 public $deleteDocumentQuestionnaireResponseList;// Array<DeleteDocumentQuestionnaireResponse>


    /**
     * 
     */
	 public $mergeTemplateResponseList;// Array<MergeTemplateResponse>


    /**
     * 
     */
	 public $deleteDocumentQuestionnaireResultList;// Array<DeleteDocumentQuestionnaireResult>


    /**
     * 
     */
	 public $getQuestionnairesResultList;// Array<GetQuestionnairesResult>


    /**
     * 
     */
	 public $getQuestionnaireExecutionsResponseList;// Array<GetQuestionnaireExecutionsResponse>


    /**
     * 
     */
	 public $deleteQuestionnaireResponseList;// Array<DeleteQuestionnaireResponse>


    /**
     * 
     */
	 public $questionInfoList;// Array<QuestionInfo>


    /**
     * 
     */
	 public $datasourceList;// Array<Datasource>


    /**
     * 
     */
	 public $getQuestionnaireResultList;// Array<GetQuestionnaireResult>


    /**
     * 
     */
	 public $mergeTemplateResultList;// Array<MergeTemplateResult>


    /**
     * 
     */
	 public $answerInfoList;// Array<AnswerInfo>


    /**
     * 
     */
	 public $getDatasourcesResultList;// Array<GetDatasourcesResult>


    /**
     * 
     */
	 public $updateQuestionnaireExecutionResultList;// Array<UpdateQuestionnaireExecutionResult>


    /**
     * 
     */
	 public $addDocumentDataSourceResultList;// Array<AddDocumentDataSourceResult>


    /**
     * 
     */
	 public $deleteDatasourceResultList;// Array<DeleteDatasourceResult>


    /**
     * 
     */
	 public $addDocumentQuestionnaireResultList;// Array<AddDocumentQuestionnaireResult>


    /**
     * 
     */
	 public $updateQuestionnaireResponseList;// Array<UpdateQuestionnaireResponse>


    /**
     * 
     */
	 public $addDatasourceResponseList;// Array<AddDatasourceResponse>


    /**
     * 
     */
	 public $getQuestionnaireResponseList;// Array<GetQuestionnaireResponse>


    /**
     * 
     */
	 public $datasourceFieldList;// Array<DatasourceField>


    /**
     * 
     */
	 public $renameResponseList;// Array<RenameResponse>


    /**
     * 
     */
	 public $renameResultList;// Array<RenameResult>


    /**
     * 
     */
	 public $signatureEnvelopeDocumentsResponseList;// Array<SignatureEnvelopeDocumentsResponse>


    /**
     * 
     */
	 public $signatureFieldInfoList;// Array<SignatureFieldInfo>


    /**
     * 
     */
	 public $signatureContactResponseList;// Array<SignatureContactResponse>


    /**
     * 
     */
	 public $signatureEnvelopesResultList;// Array<SignatureEnvelopesResult>


    /**
     * 
     */
	 public $signatureTemplateFieldLocationInfoList;// Array<SignatureTemplateFieldLocationInfo>


    /**
     * 
     */
	 public $signatureTemplateDocumentResultList;// Array<SignatureTemplateDocumentResult>


    /**
     * 
     */
	 public $signatureContactsResponseList;// Array<SignatureContactsResponse>


    /**
     * 
     */
	 public $signatureFieldResultList;// Array<SignatureFieldResult>


    /**
     * 
     */
	 public $signatureSignatureInfoList;// Array<SignatureSignatureInfo>


    /**
     * 
     */
	 public $signatureTemplateFieldsResponseList;// Array<SignatureTemplateFieldsResponse>


    /**
     * 
     */
	 public $signatureEnvelopeInfoList;// Array<SignatureEnvelopeInfo>


    /**
     * 
     */
	 public $signatureTemplateFieldSettingsList;// Array<SignatureTemplateFieldSettings>


    /**
     * 
     */
	 public $signatureTemplateFieldLocationSettingsList;// Array<SignatureTemplateFieldLocationSettings>


    /**
     * 
     */
	 public $signatureEnvelopeRecipientResultList;// Array<SignatureEnvelopeRecipientResult>


    /**
     * 
     */
	 public $signatureTemplateFieldResponseList;// Array<SignatureTemplateFieldResponse>


    /**
     * 
     */
	 public $signatureEnvelopesResponseList;// Array<SignatureEnvelopesResponse>


    /**
     * 
     */
	 public $signatureEnvelopeFieldInfoList;// Array<SignatureEnvelopeFieldInfo>


    /**
     * 
     */
	 public $signatureRoleInfoList;// Array<SignatureRoleInfo>


    /**
     * 
     */
	 public $signatureTemplateSettingsList;// Array<SignatureTemplateSettings>


    /**
     * 
     */
	 public $signatureTemplateFieldsResultList;// Array<SignatureTemplateFieldsResult>


    /**
     * 
     */
	 public $signatureContactsImportResultList;// Array<SignatureContactsImportResult>


    /**
     * 
     */
	 public $signatureEnvelopeFieldsResponseList;// Array<SignatureEnvelopeFieldsResponse>


    /**
     * 
     */
	 public $signatureTemplateDocumentInfoList;// Array<SignatureTemplateDocumentInfo>


    /**
     * 
     */
	 public $signatureFieldSettingsList;// Array<SignatureFieldSettings>


    /**
     * 
     */
	 public $signatureTemplateFieldInfoList;// Array<SignatureTemplateFieldInfo>


    /**
     * 
     */
	 public $signatureRolesResultList;// Array<SignatureRolesResult>


    /**
     * 
     */
	 public $signatureTemplateResultList;// Array<SignatureTemplateResult>


    /**
     * 
     */
	 public $signatureEnvelopeRecipientsResponseList;// Array<SignatureEnvelopeRecipientsResponse>


    /**
     * 
     */
	 public $signatureRolesResponseList;// Array<SignatureRolesResponse>


    /**
     * 
     */
	 public $signatureContactsImportResponseList;// Array<SignatureContactsImportResponse>


    /**
     * 
     */
	 public $signatureEnvelopeFieldsResultList;// Array<SignatureEnvelopeFieldsResult>


    /**
     * 
     */
	 public $signatureEnvelopeFieldResponseList;// Array<SignatureEnvelopeFieldResponse>


    /**
     * 
     */
	 public $signatureTemplateResponseList;// Array<SignatureTemplateResponse>


    /**
     * 
     */
	 public $signatureEnvelopeDocumentResponseList;// Array<SignatureEnvelopeDocumentResponse>


    /**
     * 
     */
	 public $signatureSignaturesResponseList;// Array<SignatureSignaturesResponse>


    /**
     * 
     */
	 public $signatureTemplatesResponseList;// Array<SignatureTemplatesResponse>


    /**
     * 
     */
	 public $signatureSignatureSettingsList;// Array<SignatureSignatureSettings>


    /**
     * 
     */
	 public $signatureEnvelopeResultList;// Array<SignatureEnvelopeResult>


    /**
     * 
     */
	 public $signatureTemplateDocumentResponseList;// Array<SignatureTemplateDocumentResponse>


    /**
     * 
     */
	 public $signatureTemplateRecipientsResultList;// Array<SignatureTemplateRecipientsResult>


    /**
     * 
     */
	 public $signatureContactResultList;// Array<SignatureContactResult>


    /**
     * 
     */
	 public $signatureEnvelopeRecipientResponseList;// Array<SignatureEnvelopeRecipientResponse>


    /**
     * 
     */
	 public $signatureTemplateRecipientsResponseList;// Array<SignatureTemplateRecipientsResponse>


    /**
     * 
     */
	 public $signatureEnvelopeFieldResultList;// Array<SignatureEnvelopeFieldResult>


    /**
     * 
     */
	 public $signatureTemplateDocumentsResultList;// Array<SignatureTemplateDocumentsResult>


    /**
     * 
     */
	 public $signatureEnvelopeResourcesResultList;// Array<SignatureEnvelopeResourcesResult>


    /**
     * 
     */
	 public $signatureEnvelopeDocumentsResultList;// Array<SignatureEnvelopeDocumentsResult>


    /**
     * 
     */
	 public $signatureTemplatesResultList;// Array<SignatureTemplatesResult>


    /**
     * 
     */
	 public $signatureEnvelopeRecipientsResultList;// Array<SignatureEnvelopeRecipientsResult>


    /**
     * 
     */
	 public $signatureFieldResponseList;// Array<SignatureFieldResponse>


    /**
     * 
     */
	 public $signatureFieldsResponseList;// Array<SignatureFieldsResponse>


    /**
     * 
     */
	 public $signatureStatusResponseList;// Array<SignatureStatusResponse>


    /**
     * 
     */
	 public $signatureEnvelopeFieldLocationInfoList;// Array<SignatureEnvelopeFieldLocationInfo>


    /**
     * 
     */
	 public $signatureContactsResultList;// Array<SignatureContactsResult>


    /**
     * 
     */
	 public $signatureEnvelopeDocumentInfoList;// Array<SignatureEnvelopeDocumentInfo>


    /**
     * 
     */
	 public $signatureTemplateRecipientInfoList;// Array<SignatureTemplateRecipientInfo>


    /**
     * 
     */
	 public $signatureTemplateDocumentsResponseList;// Array<SignatureTemplateDocumentsResponse>


    /**
     * 
     */
	 public $signatureSignatureResponseList;// Array<SignatureSignatureResponse>


    /**
     * 
     */
	 public $signatureEnvelopeDocumentResultList;// Array<SignatureEnvelopeDocumentResult>


    /**
     * 
     */
	 public $signatureTemplateFieldResultList;// Array<SignatureTemplateFieldResult>


    /**
     * 
     */
	 public $signatureTemplateInfoList;// Array<SignatureTemplateInfo>


    /**
     * 
     */
	 public $signatureSignatureResultList;// Array<SignatureSignatureResult>


    /**
     * 
     */
	 public $signatureFieldsResultList;// Array<SignatureFieldsResult>


    /**
     * 
     */
	 public $signatureContactSettingsList;// Array<SignatureContactSettings>


    /**
     * 
     */
	 public $signatureEnvelopeRecipientInfoList;// Array<SignatureEnvelopeRecipientInfo>


    /**
     * 
     */
	 public $signatureEnvelopeSettingsList;// Array<SignatureEnvelopeSettings>


    /**
     * 
     */
	 public $signatureEnvelopeFieldSettingsList;// Array<SignatureEnvelopeFieldSettings>


    /**
     * 
     */
	 public $signatureContactInfoList;// Array<SignatureContactInfo>


    /**
     * 
     */
	 public $signatureEnvelopeFieldLocationSettingsList;// Array<SignatureEnvelopeFieldLocationSettings>


    /**
     * 
     */
	 public $signatureEnvelopeResponseList;// Array<SignatureEnvelopeResponse>


    /**
     * 
     */
	 public $signatureSignaturesResultList;// Array<SignatureSignaturesResult>


    /**
     * 
     */
	 public $signatureEnvelopeResourcesResponseList;// Array<SignatureEnvelopeResourcesResponse>


}

?>