<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SignatureSignatureInputEnvelopesInputDocumentsInputRecipientInputFieldsInputLocationsInput {

  static $swaggerTypes = array(    
    'userId' => 'string',
    'envelopeId' => 'string',
    'documentId' => 'string',
    'recipientId' => 'string',
    'fieldId' => 'string',
    'locationId' => 'string'   
    );


    /**
     * User GUID
     */
	 public $userId;// string


    /**
     * Envelope GUID
     */
	 public $envelopeId;// string


    /**
     * Document GUID
     */
	 public $documentId;// string


    /**
     * Recipient GUID
     */
	 public $recipientId;// string


    /**
     * Field GUID
     */
	 public $fieldId;// string


    /**
     * Field location GUID
     */
	 public $locationId;// string


}

?>