<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class GetJobResult {

  static $swaggerTypes = array(    
    'id' => 'float',
    'documents' => 'JobDocumentsEntry',
    'status' => 'string',
    'email_results' => 'bool',
    'out_formats' => 'string',
    'requested_time' => 'int',
    'url_only' => 'bool',
    'actions' => 'string'   
    );


    /**
     * 
     */
	 public $id;// float


    /**
     * 
     */
	 public $documents;// JobDocumentsEntry


    /**
     * 
     */
	 public $status;// string


    /**
     * 
     */
	 public $email_results;// bool


    /**
     * 
     */
	 public $out_formats;// string


    /**
     * 
     */
	 public $requested_time;// int


    /**
     * 
     */
	 public $url_only;// bool


    /**
     * 
     */
	 public $actions;// string


}

?>