<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 */

class ComparisonAPI {

	function __construct($apiClient) {
	  $this->apiClient = $apiClient;
	}


	/**
	 * Compare
	 *
	 * 
	 * 
   * @param userId  User GUID
   *  @param sourceFileId  Source File GUID
   *  @param targetFileId  Target File GUID
   *  
	 * @return CompareResponse {@link CompareResponse} 
	 * @throws APIException 
	 */

	 public function Compare($userId, $sourceFileId, $targetFileId) {

		//parse inputs
		$resourcePath = "/comparison/{userId}/comparison/compare?source={sourceFileId}&target={targetFileId}";
		$resourcePath = str_replace("{format}", "json", $resourcePath);
		$resourcePath = str_replace("*", "", $resourcePath);
		$method = "GET";
        $queryParams = array();
        $headerParams = array();
    
		
		if($userId != null) {
			$resourcePath = str_replace("{userId}", $this->apiClient->toPathValue($userId), $resourcePath);
		}
		if($sourceFileId != null) {
			$resourcePath = str_replace("{sourceFileId}", $this->apiClient->toPathValue($sourceFileId), $resourcePath);
		}
		if($targetFileId != null) {
			$resourcePath = str_replace("{targetFileId}", $this->apiClient->toPathValue($targetFileId), $resourcePath);
		}

	
	

		//make the API Call
		$response = $this->apiClient->callAPI($resourcePath, $method, $queryParams, null, $headerParams);
    if(! $response){
        return null;
    }

		//create output objects if the response has more than one object
		$responseObject = $this->apiClient->deserialize($response, 'CompareResponse');
		return $responseObject;
				
				
	 }


	/**
	 * Get changes
	 *
	 * 
	 * 
   * @param userId  User GUID
   *  @param resultFileId  Comparison result file GUID
   *  
	 * @return ChangesResponse {@link ChangesResponse} 
	 * @throws APIException 
	 */

	 public function GetChanges($userId, $resultFileId) {

		//parse inputs
		$resourcePath = "/comparison/{userId}/comparison/changes?resultFileId={resultFileId}";
		$resourcePath = str_replace("{format}", "json", $resourcePath);
		$resourcePath = str_replace("*", "", $resourcePath);
		$method = "GET";
        $queryParams = array();
        $headerParams = array();
    
		
		if($userId != null) {
			$resourcePath = str_replace("{userId}", $this->apiClient->toPathValue($userId), $resourcePath);
		}
		if($resultFileId != null) {
			$resourcePath = str_replace("{resultFileId}", $this->apiClient->toPathValue($resultFileId), $resourcePath);
		}

	
	

		//make the API Call
		$response = $this->apiClient->callAPI($resourcePath, $method, $queryParams, null, $headerParams);
    if(! $response){
        return null;
    }

		//create output objects if the response has more than one object
		$responseObject = $this->apiClient->deserialize($response, 'ChangesResponse');
		return $responseObject;
				
				
	 }


	/**
	 * Get document details
	 *
	 * 
	 * 
   * @param userId  User GUID
   *  @param guid  Document GUID
   *  
	 * @return DocumentDetailsResponse {@link DocumentDetailsResponse} 
	 * @throws APIException 
	 */

	 public function GetDocumentDetails($userId, $guid) {

		//parse inputs
		$resourcePath = "/comparison/{userId}/comparison/document?guid={guid}";
		$resourcePath = str_replace("{format}", "json", $resourcePath);
		$resourcePath = str_replace("*", "", $resourcePath);
		$method = "GET";
        $queryParams = array();
        $headerParams = array();
    
		
		if($userId != null) {
			$resourcePath = str_replace("{userId}", $this->apiClient->toPathValue($userId), $resourcePath);
		}
		if($guid != null) {
			$resourcePath = str_replace("{guid}", $this->apiClient->toPathValue($guid), $resourcePath);
		}

	
	

		//make the API Call
		$response = $this->apiClient->callAPI($resourcePath, $method, $queryParams, null, $headerParams);
    if(! $response){
        return null;
    }

		//create output objects if the response has more than one object
		$responseObject = $this->apiClient->deserialize($response, 'DocumentDetailsResponse');
		return $responseObject;
				
				
	 }



}